### ISSUE TITLE
Filter doesn't work if you just select the nodes of a curve

### ISSUE THREAD

**Issue by davewhitley** [mekkablue/MakeCorner#2]
I couldn't figure out why the filter wasn't working for a while, but then I figured out that you must drag your mouse over the entire curve to select the rounded corner, instead of just selecting the 2 anchor points of the rounded corner.

To reproduce:

- Make a square
- Round one of the corners with the round corner filter 
- Select the 2 points of the rounded corner individually 
- Run the Make Corner filter
- Nothing happens

It would be nice to support my case, because selecting by dragging the mouse is sometimes not preferable because of complex shapes getting in the way.

It's confusing because if you select the points individually, it looks almost the same as when you select the entire curve:

![screen shot 2017-10-17 at 3 02 01 pm](https://user-images.githubusercontent.com/618551/31686728-9a93c55a-b34c-11e7-9c04-bc694153a4ce.png)

Selecting the entire curve:

![screen shot 2017-10-17 at 3 07 20 pm](https://user-images.githubusercontent.com/618551/31686794-e72e4b1a-b34c-11e7-90a8-ad2cf6eb9d21.png)

**Comment by mekkablue** [comment]
Phew. And simply selecting any of the handles is not an option for you? The on-curve nodes are _between_ segments, and I have to do an awful lot of crosschecking and path analysis to find out where the user really wants the corner... I’ll see what I can do.

**Comment by davewhitley** [comment]
I can select the handles. That would be great if I didn't have to select the handles though. It would definitely be more convenient.

I think if you can't do that, then there should be some sort of error message or instruction that explains about selecting the handles. Thanks for looking into this. I really appreciate your plugins!

**Comment by mekkablue** [comment]
Sorry, abandoning the idea. Too many ambiguous situations.
