### ISSUE TITLE
Non rounded coordinates of nodes

### ISSUE THREAD

**Issue by designiq** [mekkablue/MakeCorner#4]
Hi Rainer, I have a font in Adobe Illustrator. I copy-paste the shapes into Glyphs 3, change the size (I define the exact height of the glyph) and run Make Corner command (the original artwork has rounded corners). 

<img width="504" alt="nodes" src="https://user-images.githubusercontent.com/6051357/103929582-cec74780-511d-11eb-8874-04369cff84bf.png">

Position of some nodes is not rounded, you can see node position X 50, Y 124.5. I think it should be rounded as it is very difficult to spot.

**Comment by schriftgestalt** [comment]
This is not an issue with the plugin. If you paste from illustrator, the paths are not rounded on purpose (to be able to scale and adjust things without loosing to much precision). And the make corner filter is just keeping whatever precision it finds.
